Repository ultralytics/stars, pull requests merged in 2025-01, with the labels that each got.

#38 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#39 Standardize license headers in Python files
  count_stars.py
Labels: documentation

#40 Update count_stars.py
  count_stars.py
Labels: documentation

#41 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
  repos.yaml
Labels: documentation, devops
